version: "3.9"

services:
  db:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: amin
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: estate_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_container
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://aminjon:aminjon1@db:5432/estate_bd
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
