"""add_soft_delete_fields

Revision ID: add_soft_delete_fields
Revises: 087f25845a1a
Create Date: 2024-04-24 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'add_soft_delete_fields'
down_revision: Union[str, None] = '087f25845a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_participants', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('chat_participants', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_participants', 'deleted_at')
    op.drop_column('chat_participants', 'is_deleted')
    # ### end Alembic commands ### 