"""Updated models

Revision ID: 38f8d1d5f8b5
Revises: f9907a91b703
Create Date: 2025-03-10 20:56:39.037817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f8d1d5f8b5'
down_revision: Union[str, None] = 'f9907a91b703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorites_property_id_fkey', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_property_id_fkey', 'favorites', 'properties', ['property_id'], ['id'])
    # ### end Alembic commands ###
