"""add virtual tour fields

Revision ID: 20d7b234b368
Revises: 815b61c51079
Create Date: 2025-04-24 16:53:32.696973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d7b234b368'
down_revision: Union[str, None] = '815b61c51079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('virtual_tour_url', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('virtual_tour_type', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('virtual_tour_thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'virtual_tour_thumbnail')
    op.drop_column('properties', 'virtual_tour_type')
    op.drop_column('properties', 'virtual_tour_url')
    # ### end Alembic commands ###
