"""add ceiling_height to property

Revision ID: 2123be5776d6
Revises: 0b70756da2ee
Create Date: 2025-03-19 00:20:37.330586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2123be5776d6'
down_revision: Union[str, None] = '0b70756da2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('ceiling_height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'ceiling_height')
    # ### end Alembic commands ###
