"""Set ondelete cascade for history foreign key

Revision ID: 5cd39880f4b3
Revises: c2e7da3ae5f5
Create Date: 2025-03-12 21:00:38.292085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd39880f4b3'
down_revision: Union[str, None] = 'c2e7da3ae5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('history_property_id_fkey', 'history', type_='foreignkey')
    op.drop_constraint('history_user_id_fkey', 'history', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.create_foreign_key('history_user_id_fkey', 'history', 'users', ['user_id'], ['id'])
    op.create_foreign_key('history_property_id_fkey', 'history', 'properties', ['property_id'], ['id'])
    # ### end Alembic commands ###
