"""add has_balcony to property

Revision ID: 7013a02d677a
Revises: d8e3e1d940ef
Create Date: 2025-03-19 00:23:01.763397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7013a02d677a'
down_revision: Union[str, None] = 'd8e3e1d940ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('has_balcony', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'has_balcony')
    # ### end Alembic commands ###
