"""add all missing property fields

Revision ID: 9b89cc638d64
Revises: 054d1b763606
Create Date: 2025-03-19 00:27:15.961064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b89cc638d64'
down_revision: Union[str, None] = '054d1b763606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('bathroom', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('bath_type', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('heating', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('renovation', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('lifts_passenger', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('lifts_freight', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('parking', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('properties', sa.Column('prepayment', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('deposit', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('living_conditions', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('properties', sa.Column('who_rents', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('landlord_contact', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('contact_method', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('properties', sa.Column('build_year', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('furniture', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('properties', sa.Column('appliances', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('properties', sa.Column('connectivity', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'connectivity')
    op.drop_column('properties', 'appliances')
    op.drop_column('properties', 'furniture')
    op.drop_column('properties', 'build_year')
    op.drop_column('properties', 'contact_method')
    op.drop_column('properties', 'landlord_contact')
    op.drop_column('properties', 'who_rents')
    op.drop_column('properties', 'living_conditions')
    op.drop_column('properties', 'deposit')
    op.drop_column('properties', 'prepayment')
    op.drop_column('properties', 'parking')
    op.drop_column('properties', 'lifts_freight')
    op.drop_column('properties', 'lifts_passenger')
    op.drop_column('properties', 'renovation')
    op.drop_column('properties', 'heating')
    op.drop_column('properties', 'bath_type')
    op.drop_column('properties', 'bathroom')
    # ### end Alembic commands ###
