"""Set ON DELETE CASCADE for favorites foreign keys

Revision ID: a5cf41f60d1e
Revises: 7fbcf4e33f03
Create Date: 2025-03-12 20:48:13.920513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cf41f60d1e'
down_revision: Union[str, None] = '7fbcf4e33f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('favorites_property_id_fkey', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_user_id_fkey', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_user_id_fkey', 'favorites', 'users', ['user_id'], ['id'])
    op.create_foreign_key('favorites_property_id_fkey', 'favorites', 'properties', ['property_id'], ['id'])
    op.drop_column('favorites', 'created_at')
    # ### end Alembic commands ###
