"""Add first_name, last_name, phone, avatar_url to users

Revision ID: fbe607d1cf74
Revises: 1ad1a5ca1eb7
Create Date: 2025-03-11 11:22:04.755273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbe607d1cf74'
down_revision: Union[str, None] = '1ad1a5ca1eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('PRIVATE', 'AGENT', 'DEVELOPER', name='userroleenum'),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'PRIVATE'::userroleenum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PRIVATE', 'AGENT', 'DEVELOPER', name='userroleenum'),
               nullable=False,
               existing_server_default=sa.text("'PRIVATE'::userroleenum"))
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
